title: hbkse
url: "https://hbkse.dev"
permalink: /:title

markdown: kramdown
plugins:
  - jekyll-feed # todo: what does this do?

# this is to override any permalink settings and the blog post routes should just be the filename
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:slug
